Add pluginlib interfaces for using different solvers and graph visualizations
ros-perception/slam_karto pull request #13
Opened 2016-09-23 00:52 UTC by alain-m

- This PR proposes to add two pluginlib interfaces for slam_karto that facilitate using different solvers than SPA, and different graph visualizations.  If the specified plugins cannot be loaded, fallback behavior is set to load the default plugins (SPA). If it fails too, the node is shutdown.

- Header files are also moved to the include/ folder following http://www.ros.org/reps/rep-0122.html#include

- To test loading the plugins, run the slam_karto node with different `solver_type` and `visualizer_type` parameters.

Credits : @jonbinney , Liz Murphy

2017-01-18 13:44 UTC, alain-m commented
@mikeferguson is there anything preventing from merging this ? Let us know.

2017-03-29 10:01 UTC, stwirth commented
@mikeferguson 
![giphy](https://cloud.githubusercontent.com/assets/1481786/24449361/4d637380-1477-11e7-9628-a25c419ffb20.gif)

2017-12-24 19:16 UTC, lucbettaieb requested changes
LGTM for the most part!  Small nitpicks, but we should really try to adhere to the ROS style guide for the most part when possible.

I'll test it on my laptop soon, and hopefully we can get this merged in soon.

2017-12-24 19:16 UTC, lucbettaieb commented on include/slam_karto/graph_visualizer.h
> +namespace karto {
I think this needs to be linted.  Please run the ros linter and make sure it's happy, or at least happy enough.  Some of the things it recommends aren't really great.

2017-12-24 19:16 UTC, lucbettaieb commented on include/slam_karto/graph_visualizer.h
> +#endif // GRAPH_VISUALIZER_H
Make sure you have newlines at the end of your source files.  It helps render the diffs.

2017-12-24 19:16 UTC, lucbettaieb commented on src/slam_karto.cpp
>  #include "sensor_msgs/LaserScan.h"
May as well make these <'s too?

2017-12-24 19:16 UTC, lucbettaieb commented on src/slam_karto.cpp
> +  if (vis_publish_period == 0)
might be clearer to do 0.0 or make it clear 0 is a double.

2017-12-24 19:16 UTC, lucbettaieb commented on src/spa_graph_visualizer.cpp
> +  for (uint i=0; i<graph.size()/2; i++)
`size_t` would be good here.

2017-12-24 19:16 UTC, lucbettaieb commented on src/spa_solver.cpp
> +#include "ros/console.h"
`<`?

2017-12-24 19:17 UTC, lucbettaieb commented
@alain-m assign this back to me when you're done.

2018-01-16 18:59 UTC, lucbettaieb commented
@alain-m psssssst

2018-02-28 08:12 UTC, lucbettaieb commented
@alain-m @jonbinney ?

2018-06-14 21:01 UTC, lucbettaieb commented
@alain-m ?

also ping @mikeferguson

2018-10-15 20:31 UTC, alain-m commented
@lucbettaieb thanks a lot for the review. Sorry for the delay, I have had a long interruption from work over the past year, I am just catching up. I updated the PR to address your comments. Let me know if you need further improvements.

2018-10-17 18:24 UTC, lucbettaieb commented
No problem, glad to hear from you.  I'll take a look hopefully this week.

2019-10-10 18:22 UTC, lucbettaieb commented
@alain-m ... one year later...

Do you have a bagfile I could test this with?

2020-02-27 20:54 UTC, lucbettaieb commented
This is super stale.  Closing.  Sorry it never worked out ;c

2020-02-27 20:54 UTC, closed without merging

2020-03-12 14:15 UTC, alain-m commented
@lucbettaieb sorry for radio silence again, I had some more interruptions at work and don't have time to work on refreshing this at the moment. Thanks for the review anyway.

2020-03-12 19:22 UTC, lucbettaieb commented
@alain-m No problem.  If you ever would like to revisit this, please open it back up.