Transform tolerance
ros-perception/slam_karto pull request #30
Opened 2019-09-12 11:28 UTC by jeremyfix

This PR solves issue #29 by making use of the tf_expiration value in the timestamp of the map->odom published TF . 

It also adds a transform_tolerance parameter which defaults to 0.05 (the origin default used in the code) .

2019-09-12 14:14 UTC, mikeferguson requested changes
While the code did have 0.05 as the default, as you mentioned, that line was not actually being used. Let's set the default to 0.0 so that there is no change in behavior until someone sets the parameter. Thanks!

2019-09-12 14:14 UTC, mikeferguson commented on src/slam_karto.cpp
> +  private_nh_.param("transform_tolerance", tmp_tol, 0.05);
since tf_expiration was unused, we should really make this default 0.0 to avoid any change in behavior.

2019-09-12 15:58 UTC, jeremyfix commented on src/slam_karto.cpp
> +  private_nh_.param("transform_tolerance", tmp_tol, 0.05);
Ok, your are right.

2019-09-17 21:21 UTC, mikeferguson approved these changes

2019-09-17 21:21 UTC, merged